---
# Check client state file
- name: Include check state file tasks
  ansible.builtin.include_tasks: "client-check-{{ ansible_system }}.yml"

- name: Set configured state variable
  ansible.builtin.set_fact:
    icinga2_client_configured: true
  when:
    - icinga2_client_file.stat.exists
    - not icinga2_client_reinstall

# Client registration on master if not registered
- name: Include client configuration on master tasks
  ansible.builtin.include_tasks: client-configure-on-master.yml
  when: not icinga2_client_configured

# Configure client on Linux and Windows
- name: Include client configuration tasks
  ansible.builtin.include_tasks: "client-configure-{{ ansible_system }}.yml"

# Delete temp files, configure client on master and set client state file
- name: Delete temporary files from Ansible host
  ansible.builtin.file:
    path: "/tmp/ansible/{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost
  become: false
  when: not icinga2_client_configured

- name: Create the additional host var dir on master server
  ansible.builtin.file:
    path: "{{ icinga2_config_root_dir }}/additional-host-vars"
    state: directory
    owner: "{{ icinga2_master_user }}"
    group: "{{ icinga2_master_group }}"
    mode: '0750'
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  become: true

- name: Create the additional host var file if not exists
  ansible.builtin.file:
    path: "{{ icinga2_config_root_dir }}/additional-host-vars/{{ inventory_hostname }}.conf"
    state: touch
    owner: "{{ icinga2_master_user }}"
    group: "{{ icinga2_master_group }}"
    mode: '0640'
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  become: true
  notify: Reload Icinga2 on master server

- name: Configure the client file on Icinga master server
  ansible.builtin.template:
    src: client-host.conf.j2
    dest: "{{ icinga2_config_root_dir }}/zones.d/{{ icinga2_master_host }}/{{ inventory_hostname }}.conf"
    owner: root
    group: root
    mode: '0644'
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  vars:
    client_distro: "{{ icinga2_client_distro | default(ansible_distribution) }}"
  become: true
  notify: Reload Icinga2 on master server

- name: Create the client configuration state file
  ansible.windows.file:
    path: /root/.icinga2_client_configured
    state: touch
  when: not icinga2_client_configured and ansible_system == "Linux"
  notify: Reload Icinga2

- name: Create the client configuration state file
  ansible.windows.win_file:
    path: "{{ icinga2_config_root_dir }}\\.icinga2_client_configured"
    state: touch
  when: not icinga2_client_configured and ansible_os_family == "Windows"
