---
# Check client state file

- include_tasks: client-check-Linux.yml
  when: ansible_system == "Linux"

- include_tasks: client-check-Windows.yml
  when: ansible_os_family == "Windows"

- set_fact:
    icinga2_client_configured: true
  when: icinga2_client_file.stat.exists == True and icinga2_client_reinstall == False


# Client registration on master if not registered

- include_tasks: client-configure-on-master.yml
  when: icinga2_client_configured == False


# Configure client on Linux and Windows

- include_tasks: client-configure-Linux.yml
  when: ansible_system == "Linux"

- include_tasks: client-configure-Windows.yml
  when: ansible_os_family == "Windows"


# Delete temp files, configure client on master and set client state file

- name: Delete temporary files from Ansible host
  local_action:
    module: file
    path: "/tmp/ansible/{{ inventory_hostname }}"
    state: absent
  become: false
  when: icinga2_client_configured == False

- name: Configure the client file on Icinga master server
  vars:
    client_distro: "{{ icinga2_client_distro|default(ansible_distribution) }}"
  template:
    src: client-host.conf.j2
    dest: "{{ config_root_dir }}/zones.d/{{ icinga2_master_host }}/{{ inventory_hostname }}.conf"
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  become: true
  notify: Reload Icinga2 on master server

- name: Create the client configuration state file
  file:
    path: /root/.icinga2_client_configured
    state: touch
  when: icinga2_client_configured == False and ansible_system == "Linux"
  notify: Reload Icinga2

- name: Create the client configuration state file
  win_file:
    path: "{{ win_config_root_dir }}\\.icinga2_client_configured"
    state: touch
  when: icinga2_client_configured == False and ansible_os_family == "Windows"
