---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - rsync
      - nmap
      - bc
      - gpg
      - gpgv2
      - ca-certificates
    state: present

- name: Add Debian Backports Repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release | lower }}-backports main
    state: present
    filename: debian-backports
  when: ansible_distribution_release | lower == "stretch"

- name: Add Icinga Repository Key
  ansible.builtin.apt_key:
    url: https://packages.icinga.com/icinga.key
    state: present
    validate_certs: "{{ icinga2_validate_certs }}"

- name: Add Icinga APT Repository
  ansible.builtin.apt_repository:
    repo: deb http://packages.icinga.com/{{ ansible_distribution | lower }} icinga-{{ ansible_distribution_release }} main
    state: present
    filename: icinga

- name: Install Icinga 2
  ansible.builtin.package:
    name: icinga2
    state: present
  notify: Restart Icinga2

- name: Install Monitoring Plugins
  ansible.builtin.apt:
    name: "{{ icinga2_debian_monitoring_plugins }}"
    state: present
    update_cache: true

- name: Install Monitoring Libraries
  ansible.builtin.apt:
    name: "{{ icinga2_debian_monitoring_libraries }}"
    state: present
    update_cache: true
