---
- name: Install Icinga2 on Debian like systems
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family | lower in icinga2_apt_distros

- name: Install Icinga2 on CentOS like systems
  ansible.builtin.include_tasks: install-Centos.yml
  when: ansible_os_family | lower in icinga2_yum_distros

- name: Install Icinga2 on Windows
  ansible.builtin.include_tasks: install-Windows.yml
  when: ansible_os_family == "Windows"

- name: Disable Selinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_system == "Linux" and icinga2_selinux_disable

- name: Ensure Icinga is started and enabled on boot.
  ansible.builtin.service:
    name: icinga2
    state: started
    enabled: "{{ icinga2_enable_on_boot }}"
  when: ansible_system == "Linux"

- name: Ensure Icinga is started and enabled on boot.
  ansible.builtin.win_service:
    name: icinga2
    state: started
    start_mode: auto
  when: ansible_os_family == "Windows"
