---
- name: Set the package URL for 64bit systems
  ansible.builtin.set_fact:
    package_url: "{{ icinga2_win_msi_64bit }}"
  when: ansible_architecture == "64-bit"

# FIXME: check if OS really is 32 bit
- name: Set the package URL for 32bit systems
  ansible.builtin.set_fact:
    package_url: "{{ icinga2_win_msi_32bit }}"
  when: ansible_architecture != "64-bit"

- name: Install Icinga 2
  ansible.windows.win_package:
    path: "{{ package_url }}"
    product_id: "{{ icinga2_win_package_product_id }} "
    arguments: /qn /norestart
  notify: Restart Icinga2 on Windows
  tags: ['install-icinga2-stack', 'install-icinga2']
