---
- name: Check if Icinga2 service exist
  ansible.builtin.shell: service icinga2 status 
  register: icinga2_service_status
  failed_when: icinga2_service_status.rc not in [0, 1, 3, 4]

- name: Ensure Icinga2 service is stopped
  ansible.builtin.service:
    name: icinga2
    state: stopped
    enabled: false
  when: icinga2_service_status.rc == 0

# Remove packages on Debian
- name: Uninstall Icinga2 on Debian like systems
  ansible.builtin.include_tasks: purge-Debian.yml
  when: ansible_os_family | lower in icinga2_apt_distros

# Remove packages on CentOS
- name: Uninstall Icinga2 on CentOS like systems
  ansible.builtin.include_tasks: purge-Centos.yml
  when: ansible_os_family | lower in icinga2_yum_distros

- name: Remove Icinga2 files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ icinga2_config_root_dir }}"
    - "{{ icinga2_lib_dir }}"
    - "{{ icinga2_log_dir }}"

- name: Remove Icinga2 Client status file
  ansible.builtin.file:
    path: /root/.icinga2_client_configured
    state: absent
