---
- name: Uninstall Icinga2 on Linux systems
  ansible.builtin.include_tasks: purge-Linux.yml
  when: ansible_system == "Linux"

- name: Uninstall Icinga2 on Windows systems
  ansible.builtin.include_tasks: purge-Windows.yml
  when: ansible_os_family == "Windows"

- name: Deconfigure client on master server
  ansible.builtin.file:
    path: "{{ icinga2_config_root_dir }}/zones.d/{{ icinga2_master_host }}/{{ inventory_hostname }}.conf"
    state: absent
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  become: true
  when: not icinga2_purge_deconfigure_on_master
  notify: Reload Icinga2 on master server
