---
- include_tasks: purge-Linux.yml
  when: ansible_system == "Linux"

# TODO: Purge on Windows system
#- include_tasks: purge-Windows.yml
#  when: ansible_os_family == "Windows"

- name: Deconfigure client on master server
  file:
    path: "{{ icinga2_config_root_dir }}/zones.d/{{ icinga2_master_host }}/{{ inventory_hostname }}.conf"
    state: absent
  delegate_to: "{{ icinga2_master_inventory_hostname }}"
  become: true
  when: icinga2_purge_deconfigure_on_master != false
  notify: Reload Icinga2 on master server
