---
- name: Check if Icinga2 service exist
  ansible.windows.win_service:
    name: icinga2
  register: _service
  failed_when: _service is not defined

- name: Ensure Icinga2 service is stopped
  ansible.windows.win_service:
    name: icinga2
    state: stopped
    start_mode: disabled
  when: _service.exists

- name: Set the package URL for 64bit systems
  ansible.builtin.set_fact:
    _package_url: "{{ icinga2_win_msi_64bit }}"
  when: ansible_architecture == "64-bit"

# FIXME: check if OS really is 32 bit
- name: Set the package URL for 32bit systems
  ansible.builtin.set_fact:
    _package_url: "{{ icinga2_win_msi_32bit }}"
  when: ansible_architecture != "64-bit"

- name: Uninstall Icinga2
  ansible.windows.win_package:
    path: "{{ _package_url }}"
    product_id: "{{ icinga2_win_package_product_id }} "
    state: absent

- name: Remove Icinga2 directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - C:\ProgramData\icinga2
    - C:\Program Files\ICINGA2

- name: Remove Icinga2 Client status file
  ansible.windows.win_file:
    path: "{{ icinga2_config_root_dir }}\\.icinga2_client_configured"
    state: absent
