---
- name: Get default IP address
  set_fact:
    client_ip_address: "{{ icinga2_client_ip_address|default(ansible_default_ipv4.address) }}"
  when: ansible_system == "Linux"

- name: Get host variables
  set_fact:
    icinga2_client_os: "{{ ansible_system }}"
  when: ansible_system == "Linux"

- name: Set Icinga2 user and groups on CentOS-like systems
  set_fact:
    icinga2_user: "icinga"
    icinga2_group: "icinga"
  when: ansible_os_family | lower in icinga2_yum_distros
